const StationData = [
  {
    sno: 295,
    metro_ID: 4,
    station_ID: 1,
    route_ID: 1,
    station_Name: "Airport Road",
    latitude: "18.9127° N",
    longitude: "72.8213° E",
    station_Code: "AIRO",
    isJunction: "No",
  },
  {
    sno: 296,
    metro_ID: 4,
    station_ID: 2,
    route_ID: 1,
    station_Name: "Andheri",
    latitude: "18.9262° N",
    longitude: "72.8242° E",
    station_Code: "ANDH",
    isJunction: "No",
  },
  {
    sno: 297,
    metro_ID: 4,
    station_ID: 3,
    route_ID: 1,
    station_Name: "Asalpha",
    latitude: "18.9322° N",
    longitude: "72.8264° E",
    station_Code: "ASPH",
    isJunction: "No",
  },
  {
    sno: 298,
    metro_ID: 4,
    station_ID: 4,
    route_ID: 1,
    station_Name: "Azad Nagar",
    latitude: "18.9327° N",
    longitude: "72.8316° E",
    station_Code: "AZNA",
    isJunction: "No",
  },
  {
    sno: 299,
    metro_ID: 4,
    station_ID: 5,
    route_ID: 1,
    station_Name: "Chakala JB Nagar",
    latitude: "18.9408° N",
    longitude: "72.8318° E",
    station_Code: "CJBN",
    isJunction: "No",
  },
  {
    sno: 300,
    metro_ID: 4,
    station_ID: 6,
    route_ID: 1,
    station_Name: "DN Nagar",
    latitude: "18.9487° N",
    longitude: "72.8289° E",
    station_Code: "DNNG",
    isJunction: "No",
  },
  {
    sno: 301,
    metro_ID: 4,
    station_ID: 7,
    route_ID: 1,
    station_Name: "Ghatkopar",
    latitude: "18.9572° N",
    longitude: "72.8197° E",
    station_Code: "GHTP",
    isJunction: "No",
  },
  {
    sno: 302,
    metro_ID: 4,
    station_ID: 8,
    route_ID: 1,
    station_Name: "Jagruti Nagar",
    latitude: "18.9630° N",
    longitude: "72.8176° E",
    station_Code: "JANA",
    isJunction: "No",
  },
  {
    sno: 303,
    metro_ID: 4,
    station_ID: 9,
    route_ID: 1,
    station_Name: "Marol Naka",
    latitude: "18.9688° N",
    longitude: "72.8207° E",
    station_Code: "MANA",
    isJunction: "No",
  },
  {
    sno: 304,
    metro_ID: 4,
    station_ID: 10,
    route_ID: 1,
    station_Name: "Saki Naka",
    latitude: "18.9794° N",
    longitude: "72.8253° E",
    station_Code: "MAXI",
    isJunction: "No",
  },
  {
    sno: 305,
    metro_ID: 4,
    station_ID: 11,
    route_ID: 1,
    station_Name: "Versova",
    latitude: "18°59'26\" N",
    longitude: "72°49'06\" E",
    station_Code: "VEVA",
    isJunction: "No",
  },
  {
    sno: 306,
    metro_ID: 4,
    station_ID: 12,
    route_ID: 1,
    station_Name: "Western Express Highway",
    latitude: "18.9970° N",
    longitude: "72.8164° E",
    station_Code: "WEHY",
    isJunction: "No",
  },
];